// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/kzw200015/go-project-template/internal/health"
	"github.com/kzw200015/go-project-template/internal/platform/config"
	"github.com/kzw200015/go-project-template/internal/platform/database"
	"github.com/kzw200015/go-project-template/internal/platform/logger"
	"github.com/kzw200015/go-project-template/internal/server"
	"github.com/kzw200015/go-project-template/internal/user"
)

// Injectors from wire.go:

func initApp(ctx context.Context) (*app, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := logger.New(configConfig)
	pool, cleanup, err := database.NewPool(ctx, configConfig, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	handler := health.NewHandler(pool, slogLogger)
	querier := user.NewQuerier(pool)
	service := user.NewService(querier)
	userHandler := user.NewHandler(service, slogLogger)
	httpHandler := server.NewRouter(configConfig, slogLogger, handler, userHandler)
	httpServer := server.NewHTTPServer(configConfig, httpHandler)
	mainApp := newApp(configConfig, slogLogger, httpServer)
	return mainApp, func() {
		cleanup()
	}, nil
}
